#:kivy 1.0
#:import kivy kivy

<AppLayout>:
    cols: 1
    Bubble:
        arrow_pos: 'bottom_mid'
        orientation: 'horizontal'

        BubbleButton:
            text: 'Start'
            on_press: app.start_webview_button()
        BubbleButton:
            text: 'Exit'
            on_press: app.quit_app()
        BubbleButton:
            text: 'set thread numbers'
            on_press: app.getThreadNum()
    Label:
        text: 'KA Lite test'
