#:kivy 1.0
#:import kivy kivy

<AppLayout>:
    cols: 1
    Bubble:
        arrow_pos: 'bottom_mid'
        orientation: 'horizontal'
        BubbleButton:
            text: 'Start server'
            on_press: app.start_server()
        BubbleButton:
            text: 'Stop server'
            on_press: app.stop_server()
        BubbleButton:
            text: 'Bring webview'
            on_press: app.start_webview()
    Label:
        text: 'KA Lite test'
